name: CD REB

on:
  push:
    #branches:
      #- main
    tags:
      - 'v*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev doxygen graphviz git make perl software-properties-common
          sudo apt-get remove -y lcov gcc
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo ln -sf $(which gcov-14) /usr/bin/gcov
          git clone --branch v2.3.1 https://github.com/linux-test-project/lcov.git
          cd lcov
          sudo make install
          cd ..
      
      - name: Build
        run: |
          make clean
          make
      
      - name: Run Unit Tests
        run: |
          make test
      
      - name: Prepare release artifacts
        run: |
          mkdir -p release_artifacts
          cp -r reb/bin/* release_artifacts/
          cp -r aux/bin/* release_artifacts/
          tar -czf reb_release.tar.gz -C release_artifacts .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: reb_release.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
