name: CI

on:
  push:
    branches: [ "dev", "feat/*", "fix/*", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install libglew-dev
          sudo apt install libglfw3 libglfw3-dev
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Install GCC 14.2
        run: |
          wget https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
          tar -xvzf gcc-14.2.0.tar.gz
          cd gcc-14.2.0
          ./contrib/download_prerequisites
          mkdir build && cd build
          ../configure --enable-languages=c,c++ --disable-multilib
          make -j$(nproc)
          sudo make install

      - name: Verify GCC version
        run: |
          gcc --version
          g++ --version

      - name: Build project
        run: |
          make clean
          make
          
      - name: Run tests
        run: |
          make test  
